/**
 * AUTO-GENERATED by scripts/sync-schema.js — do not edit manually.
 *
 * Synced from @ours/types/src/event.ts on 2026-03-26T16:49:44.170Z
 *
 * These lists define which fields the server's Zod schema accepts in each
 * payload section. The SDK uses them to route parsed deep-link params to
 * the correct part of the event payload.
 *
 * ## Where should data go?
 *
 * - **defaultProperties** — Device/environment metadata and marketing attribution
 *   (UTMs, click IDs, OS info, etc.). These are typed fields in the server schema;
 *   unknown keys are silently stripped. Prefer this for any field that has a
 *   dedicated column in the schema.
 *
 * - **userProperties** — Visitor-level identity and consent. Also has typed fields
 *   for click IDs and UTMs (duplicated from defaultProperties for flexibility).
 *   Use for user-facing data: email, external_id, custom_properties, consent.
 *
 * - **eventProperties** — Free-form key/value pairs (Record<string, any>).
 *   Use ONLY for event-specific data that doesn't have a dedicated schema field.
 *   Do NOT put UTMs or click IDs here — they'll work but won't be queryable
 *   in the same way as defaultProperties fields.
 */

/**
 * UTM parameter names accepted in defaultProperties.
 */
export const UTM_PARAMS = [
  "utm_campaign",
  "utm_content",
  "utm_medium",
  "utm_name",
  "utm_source",
  "utm_term"
];

/**
 * Click ID / ad attribution fields accepted in defaultProperties.
 */
export const CLICK_IDS = [
  "alart",
  "aleid",
  "axwrt",
  "basis_cid",
  "clickid",
  "clid",
  "dclid",
  "epik",
  "fbc",
  "fbclid",
  "fbp",
  "gad_source",
  "gbraid",
  "gclid",
  "im_ref",
  "irclickid",
  "li_fat_id",
  "msclkid",
  "ndclid",
  "qclid",
  "rdt_cid",
  "sacid",
  "sccid",
  "ttclid",
  "twclid",
  "wbraid"
];

/**
 * All fields accepted by the defaultProperties section of the event payload.
 * Source: defaultPayload Zod schema in @ours/types/src/event.ts
 */
export const DEFAULT_PROPERTY_FIELDS = [
  "activeDuration",
  "ad_id",
  "adset_id",
  "alart",
  "aleid",
  "axwrt",
  "basis_cid",
  "browser_language",
  "browser_name",
  "browser_version",
  "campaign_id",
  "clickid",
  "clid",
  "cpu_architecture",
  "current_url",
  "dclid",
  "device_model",
  "device_type",
  "device_vendor",
  "duration",
  "encoding",
  "engine_name",
  "engine_version",
  "epik",
  "fbc",
  "fbclid",
  "fbp",
  "fv",
  "gad_source",
  "gbraid",
  "gclid",
  "host",
  "iframe",
  "im_ref",
  "ip",
  "irclickid",
  "is_bot",
  "li_fat_id",
  "msclkid",
  "ndclid",
  "new_s",
  "os_name",
  "os_version",
  "page_hash",
  "pathname",
  "qclid",
  "rdt_cid",
  "received_at",
  "referrer",
  "referring_domain",
  "sacid",
  "sccid",
  "screen_height",
  "screen_width",
  "sessionCount",
  "sid",
  "sr",
  "title",
  "ttclid",
  "twclid",
  "uafvl",
  "user_agent",
  "utm_campaign",
  "utm_content",
  "utm_medium",
  "utm_name",
  "utm_source",
  "utm_term",
  "version",
  "wbraid",
  "webview"
];

/**
 * All fields accepted by the userProperties section of the event payload.
 * Source: externalVisitorProperties Zod schema in @ours/types/src/event.ts
 */
export const USER_PROPERTY_FIELDS = [
  "ad_id",
  "adset_id",
  "alart",
  "aleid",
  "axwrt",
  "basis_cid",
  "campaign_id",
  "city",
  "clickid",
  "clid",
  "company_name",
  "consent",
  "country",
  "custom_properties",
  "date_of_birth",
  "dclid",
  "email",
  "epik",
  "external_id",
  "fbc",
  "fbclid",
  "fbp",
  "first_name",
  "gad_source",
  "gbraid",
  "gclid",
  "gender",
  "im_ref",
  "ip",
  "irclickid",
  "is_bot",
  "job_title",
  "last_name",
  "li_fat_id",
  "msclkid",
  "ndclid",
  "phone_number",
  "qclid",
  "rdt_cid",
  "referrer",
  "referring_domain",
  "sacid",
  "sccid",
  "sid",
  "state",
  "ttclid",
  "twclid",
  "user_agent",
  "user_agent_full_list",
  "utm_campaign",
  "utm_content",
  "utm_medium",
  "utm_name",
  "utm_source",
  "utm_term",
  "wbraid",
  "zip"
];

/**
 * Schema sync timestamp. Use in CI to detect staleness.
 */
export const SCHEMA_SYNCED_AT = "2026-03-26T16:49:44.170Z";
