platform :ios, '10.0'

target 'OursPrivacyReactNative' do
  use_frameworks!
  config = use_native_modules!

  # This pulls in pods for all your RN dependencies automatically
  use_react_native!(:path => config["reactNativePath"])

  # Add your custom module if it's local
  pod 'OursPrivacyReactNative', :path => '../oursprivacy-react-native'

end
